### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by champeau87** [ValhelsiaTeam/Valhelsia-Origins#1]
[crash-2020-07-08_02.01.50-server.txt](https://github.com/ValhelsiaTeam/Valhelsia-Origins/files/4888092/crash-2020-07-08_02.01.50-server.txt)

Crash report from my server.  Not sure if it is something you guys would handle or the specific mod, but here is the crash report.

**Comment by Vaelzan** [comment]
It will be fixed in the next version, aimed at being released tomorrow.

**Comment by Vaelzan** [comment]
Fixed in 1.0.1.
