### ISSUE TITLE
Issue with HealthOverlay on startup

### ISSUE THREAD

**Issue by Lollerix** [ValhelsiaTeam/Valhelsia-Origins#10]
I installed the modpack through the server installer. It automatically disabled some jars that i then re-enabled, otherwise we couldn't connect to the server. Now on startup i get an error "Caught exception during event FMLCommonSetupEvent dispatch for modid healthoverlay" what could it be?

**Comment by Vaelzan** [comment]
What do you mean by server installer?

**Comment by Vaelzan** [comment]
Also, Health Overlay is quite deliberately not in our server pack because it doesn't work on a server. If you have it on the server, then the server isn't installed correctly, and wasn't installed via our provided server pack.

**Comment by Lollerix** [comment]
The server provider i'm using has a browser for the modpacks to install them easily. If you're telling me that the server shouldn't have that mod then i need to find how to install the server pack manually
