### ISSUE TITLE
Create Minecart Contraption Kicking Player

### ISSUE THREAD

**Issue by natintin** [ValhelsiaTeam/Valhelsia-Origins#12]
Hello.  I'm hoping I can find some resolution to this issue.  Me and my cousin have been playing on a private server I have set up using the Bisect Premium panel and selecting the modpack from the list.  Everything has been running great without any issues except now.  I made a minecart contraption with create that has drills on the front to do large amounts of mining.  Whenever I place the minecart contraption my cousin instantly is kicked from the server.  He is not able to long back in until I use the engineers wrench on the contraption to put it back in my inventory.  Once in my inventory he's able to log back in.  He's already tried reinstalling the pack.  Any suggestions?  Thanks.

**Comment by Vaelzan** [comment]
Hey. Thanks for the report. We'll be releasing a pack update in the near future (within a week or so) that I think resolves that, but in the mean time you can manually update the version of Create in the pack (for all players and the server) to the latest version - Create 0.3e.

**Comment by natintin** [comment]
Thanks for the quick reply!  I think we'll wait for the update as we have a ton of other things to work on in our world.  Also great job with this pack.  It runs very well and has a really good balance of mods.  We've been having a blast!

**Comment by Vaelzan** [comment]
Thank you for the kind words. :) 

I've put a lot of hard work into it so I'm really glad to hear that you're enjoying it. I hope you like the update too, it only adds a few small new mods but some of them can be quite fun (and of course, there's a lot of bug fixes!).
