### ISSUE TITLE
Crash on worldgen v1.0.1

### ISSUE THREAD

**Issue by Scritches** [ValhelsiaTeam/Valhelsia-Origins#2]
Pack loads fine but then crashes when I generate a world. I'm not really sure what's going on but here's the log in case this is something you guys can use. I'm using MultiMC to launch the pack. If there's more you need from me please let me know:

---- Minecraft Crash Report ----
// Oops.

Time: 7/9/20, 1:58 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at com.ldtteam.structurize.util.StructureUtils.calculateMD5(StructureUtils.java:48) ~[?:0.13.4-ALPHA] {re:classloading}
	at com.ldtteam.structurize.util.StructureUtils.calculateMD5(StructureUtils.java:108) ~[?:0.13.4-ALPHA] {re:classloading}
	at com.ldtteam.structurize.management.Structures.loadSchematicsForPrefix(Structures.java:333) ~[?:0.13.4-ALPHA] {re:classloading}
	at com.ldtteam.structurize.management.Structures.loadStyleMapsJar(Structures.java:238) ~[?:0.13.4-ALPHA] {re:classloading}
	at com.ldtteam.structurize.management.Structures.loadStyleMaps(Structures.java:145) ~[?:0.13.4-ALPHA] {re:classloading}
	at com.ldtteam.structurize.management.Structures.init(Structures.java:122) ~[?:0.13.4-ALPHA] {re:classloading}
	at com.ldtteam.structurize.event.EventSubscriber.onServerStarting(EventSubscriber.java:58) ~[?:0.13.4-ALPHA] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_186_EventSubscriber_onServerStarting_Load.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraft.server.MinecraftServer.func_213194_a(MinecraftServer.java:414) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:96) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:832) ~[?:?] {}
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
	at java.lang.ClassLoader.findClass(ClassLoader.java:719) ~[?:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:92) ~[modlauncher-5.1.0.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?] {}
	... 15 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Linux (amd64) version 5.7.7-arch1-1
	Java Version: 14.0.1, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1645574784 bytes (1569 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 12
	JVM Flags: 2 total; -Xms2048m -Xmx4096m
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.31-launcher.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.31-launcher.jar runtime_enum_extender PLUGINSERVICE 
		/forge-1.15.2-31.2.31-launcher.jar capability_inject_definalize PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.31-launcher.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.2.31-launcher.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.31
	FML Language Providers: 
		javafml@31.2
		minecraft@1
		kotlinfml@1.5.2
	Mod List: 
		enchantedbookredesign-2.0.jar Enchanted Book Redesign {enchantedbookredesign@2.0 DONE}
		NetherPortalFix_1.15.2-6.0.2.jar NetherPortalFix {netherportalfix@6.0.2 DONE}
		scenic-1.15.2-1.0.0.jar Scenic {scenic@1.15.2-1.0.0 DONE}
		curiousshulkerboxes-FORGE-1.15.2-2.0.1.jar Curious Shulker Boxes {curiousshulkerboxes@FORGE-1.15.2-2.0.1 DONE}
		mcw-windows-1.0.1-mc1.15.2_1.15.1.jar Macaw's Windows {mcwwindows@1.0.1 DONE}
		Neat 1.6-22.jar Neat {neat@1.6-22 DONE}
		BetterTitleScreen-1.15.2-1.9.jar Better Title Screen {bettertitlescreen@1.15.2-1.9 DONE}
		XaerosWorldMap_1.7.2_Forge_1.15.2.jar Xaero's World Map {xaeroworldmap@1.7.2 DONE}
		CookingForBlockheads_1.15.2-8.0.3.jar Cooking for Blockheads {cookingforblockheads@8.0.3 DONE}
		Controlling-6.1.5.6.jar Controlling {controlling@6.1.5.6 DONE}
		ReAuth-1.14-1.15-3.8.1.jar ReAuth {reauth@3.8.1 DONE}
		Placebo-1.15.2-3.1.0.jar Placebo {placebo@3.1.0 DONE}
		Bookshelf-1.15.2-5.6.40.jar Bookshelf {bookshelf@5.6.40 DONE}
		randompatches-1.15.2-1.22.0.0.jar RandomPatches {randompatches@1.15.2-1.22.0.0 DONE}
		mcw-doors-1.0.0-mc1.15.2.jar Macaw's Doors {mcwdoors@1.0.0 DONE}
		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version DONE}
		JustEnoughResources-1.15.2-0.10.1.77.jar Just Enough Resources {jeresources@0.10.1.77 DONE}
		absentbydesign-1.15.2-1.1.0.jar Absent By Design Mod {absentbydesign@1.15.2-1.1.0 DONE}
		structure-gel-api-1.15.2-1.1.0.jar Structure Gel API {structure_gel@1.1.0 DONE}
		PackMenu-1.15.2-1.2.4.jar Pack Menu {packmenu@1.2.4 DONE}
		torchmaster-2.2.1.jar Torchmaster {torchmaster@2.2.1 DONE}
		AmbientSounds_v3.0.20_mc1.15.2.jar Ambient Sounds {ambientsounds@3.0.3 DONE}
		BetterDrowning-1.15.2-1.0.3.jar BetterDrowning {betterdrowning@1.0.3 DONE}
		phosphor-forge-mc1.15.2-0.5.2+build.4.jar Phosphor {phosphor@0.5.2+build.4 DONE}
		valhelsia_structures-15.0.3a.jar Valhelsia Structures {valhelsia_structures@15.0.3a DONE}
		toughnessbar-5.0.jar Toughness Bar {toughnessbar@5.0 DONE}
		Modpack Configuration Checker-1.15.x-v1.9.5.jar Modpack Config Checker {concheckrmd@1.9.5 DONE}
		fairylights-3.0.4-1.15.2.jar Fairy Lights {fairylights@3.0.4 DONE}
		curios-FORGE-1.15.2-2.0.2.4.jar Curios API {curios@FORGE-1.15.2-2.0.2.4 DONE}
		tetra-1.15.2-2.15.0.jar Tetra {tetra@1.15.2-2.15.0 DONE}
		Botania-r1.15-387.jar Botania {botania@r1.15-387 DONE}
		Patchouli-1.15.2-1.2-34.jar Patchouli {patchouli@1.15.2-1.2-34 DONE}
		leap-1.15.2-1.0.1.jar Leap {leap@1.0.1 DONE}
		config-2-3.0.jar Cloth Config v2 API {cloth-config2@3.0 DONE}
		mcw-roofs-1.0.2-mc1.15.2_1.15.1.jar Macaw's Roofs {mcwroofs@1.0.2 DONE}
		curiouselytra-FORGE-1.15.2-2.0.jar Curious Elytra {curiouselytra@FORGE-1.15.2-2.0 DONE}
		cc-tweaked-1.15.2-1.89.1.jar CC: Tweaked {computercraft@1.89.1 DONE}
		AI-Improvements-1.15.2-0.3.0.jar AI-Improvements {aiimprovements@0.3.0 DONE}
		cherishedworlds-FORGE-1.15.2-3.0.0.1.jar Cherished Worlds {cherishedworlds@FORGE-1.15.2-3.0.0.1 DONE}
		tramplestopper-1.15.2-2.0.0.1-universal.jar Trample Stopper {tramplestopper@1.15.2-2.0.0.1-universal DONE}
		BetterBurning-1.15.2-1.3.4.jar BetterBurning {betterburning@1.3.4 DONE}
		bwncr-1.15.1-3.6.13.jar Bad Wither No Cookie Reloaded {bwncr@1.15.1-3.6.13 DONE}
		bettertridentreturn-1.15.2-1.0.1.jar Better Trident Return {bettertridentreturn@1.0.1 DONE}
		incubation-1.0.4-1.15.2.jar Incubation {incubation@1.0.4 DONE}
		FastLeafDecay-v22.jar FastLeafDecay {fastleafdecay@v22 DONE}
		CodeChickenLib-1.15.2-3.3.0.373-universal.jar CodeChicken Lib {codechickenlib@3.3.0.373 DONE}
		ServerTabInfo-1.15.2-1.2.7.jar Server Tab Info {servertabinfo@1.2.7 DONE}
		BetterMineshaftsForge-1.15.2-1.0.2.jar YUNG's Better Mineshafts {bettermineshafts@1.15.2-1.0.2 DONE}
		leavesdecayonotherleaves-1.1.jar Leaves Decay on other Leaves {leavesdecayonotherleaves@1.1 DONE}
		BetterAdvancements-1.15.2-0.1.0.99.jar Better Advancements {betteradvancements@0.1.0.99 DONE}
		CraftPresence-1.15.2-1.6.5.jar CraftPresence {craftpresence@1.6.5 DONE}
		SaveMyStronghold-1.15.2-1.0.1.jar Save My Stronghold! {savemystronghold@1.15.2-1.0.1 DONE}
		QuarkOddities-1.15.2.jar Quark Oddities {quarkoddities@1.15.2 DONE}
		inventorysorter-1.15.2-17.0.0.jar Simple Inventory Sorter {inventorysorter@17.0.0 DONE}
		ClientTweaks_1.15.2-4.1.2.jar Client Tweaks {clienttweaks@4.1.2 DONE}
		TrashSlot_1.15.2-11.0.0.jar TrashSlot {trashslot@11.0.0 DONE}
		torchslabmod-1.15.2_v1.7.0.jar Torch Slab Mod {torchslabmod@1.7.0 DONE}
		EquipmentTooltips-1.15.2-1.4.3+14.jar Equipment Tooltips {equipmenttooltips@1.4.3+14 DONE}
		berry_good-2.0.0.jar Berry Good {berry_good@2.0 DONE}
		PersistentBits-1.15.2-2.0.3.jar Persistent Bits {persistentbits@2.0.3 DONE}
		jei-1.15.2-6.0.2.12.jar Just Enough Items {jei@6.0.2.12 DONE}
		worleycaves-1.15.2-1.6.0.jar Worley's Caves {worleycaves@1.15.2-1.6.0 DONE}
		Druidcraft-1.15-0.4.21.jar Druidcraft {druidcraft@0.4.21 DONE}
		AttributeFix-1.15.2-7.0.2.jar AttributeFix {attributefix@7.0.2 DONE}
		the-conjurer-1.15.2-1.0.6.jar The Conjurer {conjurer_illager@1.0.6 DONE}
		Abnormals-Core-1.15.2-1.0.6.jar Abnormals Core {abnormals_core@1.0.6 DONE}
		Buzzier-Bees-1.15.2-1.5.2.jar Buzzier Bees {buzzierbees@1.5.2 DONE}
		goblintraders-1.2.0-1.15.2.jar Goblin Traders {goblintraders@1.2.0 DONE}
		caelus-FORGE-1.15.2-2.0-beta3.jar Caelus API {caelus@FORGE-1.15.2-2.0-beta3 DONE}
		Upgrade-Aquatic-1.15.2-1.7.1.jar Upgrade Aquatic {upgrade_aquatic@1.7.1 DONE}
		WAWLA-1.15.2-3.0.3.jar WAWLA {wawla@3.0.3 DONE}
		extraboats-1.3.6-1.15.2.jar Extra Boats {extraboats@1.3.6 DONE}
		create-mc1.15.2_v0.2.4d.jar Create {create@mc1.15.2_v0.2.4d DONE}
		Waystones_1.15.2-6.0.2.jar Waystones {waystones@6.0.2 DONE}
		Clumps-5.0.2.jar Clumps {clumps@5.0.2 DONE}
		mgui-1.15.2-2.1.1.jar mgui {mgui@2.1.1 DONE}
		light-overlay-4.7.0.jar Light Overlay Forge {lightoverlay-forge@NONE DONE}
		NaturesCompass-1.15.2-1.8.5.jar Nature's Compass {naturescompass@1.15.2-1.8.5 DONE}
		decorative_blocks-6d.jar Decorative Blocks {decorative_blocks@1.6 DONE}
		curioofundying-FORGE-1.15.2-3.0.jar Curio of Undying {curioofundying@FORGE-1.15.2-3.0 DONE}
		snowundertrees-1.15.2-v1.1.1.jar Snow Under Trees {snowundertrees@v1.1.1 DONE}
		bedspreads-FORGE-1.15.2-3.0.0.1.jar Bedspreads {bedspreads@FORGE-1.15.2-3.0.0.1 DONE}
		trash-1.15.2-0.1.4.jar Trash {trash@1.15.2-0.1.4 DONE}
		ToastControl-1.15.2-3.0.1.jar Toast Control {toastcontrol@3.0.1 DONE}
		EnderStorage-1.15.2-2.5.0.143-universal.jar EnderStorage {enderstorage@2.5.0.143 DONE}
		CraftTweaker-1.15.2-6.0.0.31.jar CraftTweaker {crafttweaker@6.0.0.31 DONE}
		Swamp-Expansion-1.15.2-1.7.3.jar Swamp Expansion {swampexpansion@NONE DONE}
		forge-1.15.2-31.2.31-universal.jar Forge {forge@31.2.31 DONE}
		Ceramics-1.15.2-1.4.0.jar Ceramics {ceramics@1.15.2-1.4.0 DONE}
		WailaHarvestability-mc1.15.2-1.1.12.jar Waila Harvestability {wailaharvestability@1.1.12 DONE}
		dash-1.15.2-1.0.1.jar Dash {dash@1.0.1 DONE}
		sounddeviceoptions-1.3.0.jar Sound Device Options {sounddeviceoptions@1.3.0 DONE}
		CraftingTweaks_1.15.2-11.0.1.jar Crafting Tweaks {craftingtweaks@11.0.1 DONE}
		forge-1.15.2-31.2.31-client.jar Minecraft {minecraft@1.15.2 DONE}
		cofh_core-1.15.2-0.4.0b.jar CoFH Core {cofh_core@0.4.0b DONE}
		ensorcellation-1.15.2-0.4.1b.jar Ensorcellation {ensorcellation@0.4.1b DONE}
		The-Endergetic-Expansion-1.15.2-v1.3.2.jar The Endergetic Expansion {endergetic@1.3.2 DONE}
		blocklayering-1.15.2-1.0.0.jar Block Layering {blocklayering@1.15.2-1.0.0 DONE}
		swingthroughgrass-1.15.2-1.4.0.jar SwingThroughGrass {swingthroughgrass@1.15.2-1.4.0 DONE}
		MouseTweaks-2.13-mc1.15.1.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		Psi r1.2-82.jar Psi {psi@r1.2-80 DONE}
		ImmersiveEngineering-0.15-103.jar Immersive Engineering {immersiveengineering@0.15-101 DONE}
		forbidden_arcanus-1.15.2-1.4.jar Forbidden & Arcanus {forbidden_arcanus@1.15.2-1.4 DONE}
		archers_paradox-1.15.2-0.4.0b.jar Archer's Paradox {archers_paradox@0.4.0b DONE}
		Atmospheric-1.15.2-1.4.1.jar Atmospheric {atmospheric@1.4.1 DONE}
		paintings-1.15.2-7.0.0.0.jar Paintings ++ {paintings@1.14.4-6.0.1.5 DONE}
		jeiintegration_1.15.2-3.1.0.1.jar JEI Integration {jeiintegration@3.1.0.1 DONE}
		Savage-and-Ravage-1.15.2-1.1.4.jar Savage & Ravage {savageandravage@1.1.4 DONE}
		Xaeros_Minimap_20.15.2_Forge_1.15.2.jar Xaero's Minimap {xaerominimap@20.15.2 DONE}
		JAOPCA-1.15.2-3.2.0.11.jar JAOPCA {jaopca@3.2.0.11 DONE}
		ftb-backups-2.1.0.1.jar FTB Utilities: Backups {ftbbackups@2.1.0.1 DONE}
		FastWorkbench-1.15.1-3.0.0.jar FastWorkbench {fastbench@3.0.0 DONE}
		autumnity-1.3.3-1.15.2.jar Autumnity {autumnity@1.3.3 DONE}
		polymorph-FORGE-1.15.2-0.3.jar Polymorph {polymorph@FORGE-1.15.2-0.3 DONE}
		AutoRegLib-1.5-40.jar AutoRegLib {autoreglib@1.5-40 DONE}
		AkashicTome-1.3-13.jar Akashic Tome {akashictome@1.3-13 DONE}
		Quark-r2.1-245.jar Quark {quark@r2.1-245 DONE}
		Charm-1.15.2-1.5.9.jar Charm {charm@1.15.2-1.5.9 DONE}
		Charmonium-1.15.2-1.0.1.jar Charmonium {charmonium@1.15.2-1.0.1 DONE}
		Covalent-1.15.2-1.0.2.jar Covalent {covalent@1.15.2-1.0.2 DONE}
		Enhanced-Mushrooms-1.15.2-v1.2.2.jar Enhanced Mushrooms {enhanced_mushrooms@$1.1.0 DONE}
		Strange-1.15.2-1.0.0-beta.5.hotfix1.jar Strange {strange@1.15.2-1.0.0-beta.5 DONE}
		StorageDrawers-1.15.2-7.0.2.jar Storage Drawers {storagedrawers@1.15.2-7.0.1 DONE}
		DoubleSlabs-1.15-2.7.6.jar Double Slabs {doubleslabs@2.7.6 DONE}
		structurize-0.13.4-ALPHA.jar Structurize {structurize@0.13.4-ALPHA DONE}
		FastFurnace-1.15.1-3.0.0.jar FastFurnace {fastfurnace@3.0.0 DONE}
		AppleSkin-mc1.15.2-forge-1.0.14.jar AppleSkin {appleskin@1.0.14 DONE}
		engineersdecor-1.15.2-1.1.0.jar Engineer's Decor {engineersdecor@1.1.0 DONE}
		CosmeticArmorReworked-1.15.2-v3a.jar CosmeticArmorReworked {cosmeticarmorreworked@1.15.2-v3a DONE}
		SoundFilters-0.13_for_1.15.2.jar Sound Filters {soundfilters@0.13_for_1.15.2 DONE}
		overloadedarmorbar-4.0.0.jar Overloaded Armor Bar {overloadedarmorbar@4.0.0 DONE}
		createintegration-0.1.7b.jar Create Integration {createintegration@0.1.7b DONE}
		step-1.15.2-1.0.2.jar Step {step@1.0.2 DONE}
		OpenLoader-1.15.2-4.0.5.jar OpenLoader {openloader@4.0.5 DONE}
		DefaultOptions_1.15.2-11.0.1.jar Default Options {defaultoptions@11.0.1 DONE}
	[Psi] Active spell: None
	Patchouli open book context: n/a
	Player Count: 0 / 8; []
	Data Packs: vanilla, inmemory:jaopca (incompatible), mod:enchantedbookredesign, mod:netherportalfix (incompatible), mod:scenic, mod:curiousshulkerboxes (incompatible), mod:mcwwindows, mod:neat (incompatible), mod:bettertitlescreen, mod:xaeroworldmap, mod:cookingforblockheads (incompatible), mod:controlling (incompatible), mod:reauth (incompatible), mod:placebo (incompatible), mod:bookshelf (incompatible), mod:randompatches (incompatible), mod:mcwdoors, mod:waila (incompatible), mod:jeresources (incompatible), mod:absentbydesign (incompatible), mod:structure_gel, mod:packmenu (incompatible), mod:torchmaster (incompatible), mod:ambientsounds (incompatible), mod:betterdrowning (incompatible), mod:phosphor, mod:valhelsia_structures (incompatible), mod:toughnessbar (incompatible), mod:concheckrmd, mod:fairylights, mod:curios (incompatible), mod:tetra, mod:botania (incompatible), mod:patchouli (incompatible), mod:leap (incompatible), mod:cloth-config2 (incompatible), mod:mcwroofs, mod:curiouselytra (incompatible), mod:computercraft (incompatible), mod:aiimprovements (incompatible), mod:cherishedworlds (incompatible), mod:tramplestopper (incompatible), mod:betterburning (incompatible), mod:bwncr (incompatible), mod:bettertridentreturn (incompatible), mod:incubation, mod:fastleafdecay, mod:codechickenlib (incompatible), mod:servertabinfo (incompatible), mod:bettermineshafts (incompatible), mod:leavesdecayonotherleaves, mod:betteradvancements (incompatible), mod:craftpresence, mod:savemystronghold (incompatible), mod:quarkoddities, mod:inventorysorter (incompatible), mod:clienttweaks (incompatible), mod:trashslot (incompatible), mod:torchslabmod, mod:equipmenttooltips (incompatible), mod:berry_good (incompatible), mod:persistentbits (incompatible), mod:jei (incompatible), mod:worleycaves (incompatible), mod:druidcraft, mod:attributefix (incompatible), mod:conjurer_illager, mod:abnormals_core, mod:buzzierbees, mod:goblintraders, mod:caelus (incompatible), mod:upgrade_aquatic (incompatible), mod:wawla (incompatible), mod:extraboats, mod:create, mod:waystones (incompatible), mod:clumps (incompatible), mod:mgui (incompatible), mod:lightoverlay-forge (incompatible), mod:naturescompass (incompatible), mod:decorative_blocks, mod:curioofundying (incompatible), mod:snowundertrees (incompatible), mod:bedspreads (incompatible), mod:trash, mod:toastcontrol (incompatible), mod:enderstorage (incompatible), mod:crafttweaker (incompatible), mod:swampexpansion (incompatible), mod:forge (incompatible), mod:ceramics (incompatible), mod:wailaharvestability (incompatible), mod:dash (incompatible), mod:sounddeviceoptions (incompatible), mod:craftingtweaks (incompatible), mod:cofh_core (incompatible), mod:ensorcellation (incompatible), mod:endergetic (incompatible), mod:blocklayering (incompatible), mod:swingthroughgrass (incompatible), mod:mousetweaks (incompatible), mod:psi (incompatible), mod:immersiveengineering (incompatible), mod:forbidden_arcanus, mod:archers_paradox (incompatible), mod:atmospheric, mod:paintings (incompatible), mod:jeiintegration (incompatible), mod:savageandravage, mod:xaerominimap, mod:jaopca (incompatible), mod:ftbbackups (incompatible), mod:fastbench (incompatible), mod:autumnity, mod:polymorph, mod:autoreglib (incompatible), mod:akashictome (incompatible), mod:quark, mod:charm (incompatible), mod:charmonium (incompatible), mod:covalent (incompatible), mod:enhanced_mushrooms, mod:strange (incompatible), mod:storagedrawers (incompatible), mod:doubleslabs, mod:structurize (incompatible), mod:fastfurnace (incompatible), mod:appleskin (incompatible), mod:engineersdecor, mod:cosmeticarmorreworked (incompatible), mod:soundfilters (incompatible), mod:overloadedarmorbar (incompatible), mod:createintegration (incompatible), mod:step (incompatible), mod:openloader (incompatible), mod:defaultoptions (incompatible), openloader/Valhelsia_Origins-Recipes, openloader/Valhelsia_Origins-Tetra
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
[m[32m[13:58:40] [Render thread/INFO] [STDOUT/]: [net.minecraft.util.registry.Bootstrap:func_179870_a:103]: #@!@# Game crashed! Crash report saved to: #@!@# /home/scritch/.local/share/multimc/instances/file/minecraft/crash-reports/crash-2020-07-09_13.58.40-server.txt
[m[32m[13:58:40] [CraftPresence-ShutDown-Handler/INFO] [STDERR/]: [com.gitlab.cdagaming.craftpresence.utils.discord.DiscordUtils:shutDown:403]: java.lang.IllegalStateException: IPCClient (ID: 723942716915974145) is not connected!
[m[32m[13:58:40] [CraftPresence-ShutDown-Handler/INFO] [STDERR/]: [com.gitlab.cdagaming.craftpresence.utils.discord.DiscordUtils:shutDown:403]: 	at com.gitlab.cdagaming.craftpresence.utils.discord.rpc.IPCClient.checkConnected(IPCClient.java:384)
[m[32m[13:58:40] [CraftPresence-ShutDown-Handler/INFO] [STDERR/]: [com.gitlab.cdagaming.craftpresence.utils.discord.DiscordUtils:shutDown:403]: 	at com.gitlab.cdagaming.craftpresence.utils.discord.rpc.IPCClient.close(IPCClient.java:325)
[m[32m[13:58:40] [CraftPresence-ShutDown-Handler/INFO] [STDERR/]: [com.gitlab.cdagaming.craftpresence.utils.discord.DiscordUtils:shutDown:403]: 	at com.gitlab.cdagaming.craftpresence.utils.discord.DiscordUtils.shutDown(DiscordUtils.java:401)
[m[32m[13:58:40] [CraftPresence-ShutDown-Handler/INFO] [STDERR/]: [com.gitlab.cdagaming.craftpresence.utils.discord.DiscordUtils:shutDown:403]: 	at com.gitlab.cdagaming.craftpresence.utils.discord.DiscordUtils$1.run(DiscordUtils.java:178)
[m[32m[13:58:40] [CraftPresence-ShutDown-Handler/INFO] [craftpresence/]: Shutting Down CraftPresence...
Exception in thread "Immersive Engineering Registry Iteration Thread" Exception in thread "Immersive Engineering Registry Iteration Thread" AL lib: (EE) alc_cleanup: 1 device not closed

Process exited with code 255.

**Comment by Scritches** [comment]
So this is probably a MultiMC issue and not an issue with your pack; I tried again with atlauncher and it runs fine. Thanks guys. =)

**Comment by Vaelzan** [comment]
It was a Java version issue. Modded Minecraft relies on Java 8. Presumably ATLauncher was running the pack with a different version.

**Comment by Scritches** [comment]
That's funny - I considered that, and I had switched my Java version to version 8 before launching the pack, but I didn't restart MultiMC itself after switching versions - so while the game was running version 8, MultiMC was still running version 14. ATLauncher does indeed run version 8.

I might give MultiMC another shot but so far I'm happy with ATLauncher, heh. Thanks for the update :3
