### ISSUE TITLE
Server Crash: java.lang.NoClassDefFoundError When starting server version 1.1.1

### ISSUE THREAD

**Issue by Jet-29** [ValhelsiaTeam/Valhelsia-Origins#7]
log: https://pastebin.com/BC7aqbQE

The server throws this error immediately after executing the ServerStart.sh 

command: `java -jar -Xms10G -Xmx12G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:G1MixedGCLiveThresholdPercent=50 -XX:+AlwaysPreTouch forge-1.15.2-31.2.41.jar nogui` 

Java installed:
`java version "15" 2020-09-15
Java(TM) SE Runtime Environment (build 15+36-1562)
Java HotSpot(TM) 64-Bit Server VM (build 15+36-1562, mixed mode, sharing)`

It is running on ubuntu 20 inside a virtual machine

**Comment by ScottKillen** [comment]
Minecraft requires java version 8. The version you are running (15) was just released two weeks ago.
