### ISSUE TITLE
Immersive Engineering Crash

### ISSUE THREAD

**Issue by thetunkery** [ValhelsiaTeam/Valhelsia-Origins#8]
The version of Immersive Engineering in the pack (1.15.2-4.0.1-119) has a known bug on servers where the wires cause crashes on loading chunks. The issue can be seen raised with the mod developer [here](https://github.com/BluSunrize/ImmersiveEngineering/issues/4276#issuecomment-699617966).

The issue was fixed for the next release available for 1.15.2 (4.1.0-122). Please could this be updated for the next version of the modpack?

**Comment by Vaelzan** [comment]
That version of IE is already in the development version of Valhelsia: Origins 1.1.2. I'm just hoping for a new DoubleSlabs release (to fix a critical bug) before the update is made public.

If you want, you can message me on Discord to get a preview version of the pack update before it's uploaded to CurseForge.
