### ISSUE TITLE
Valhelsia 3 Not Opening

### ISSUE THREAD

**Issue by keremlov** [ValhelsiaTeam/Valhelsia-Origins#9]
I have been playing Valhelsia 3 (Latest version) and one day when I wake up I couldn't pass the screen after the 'reading data' screen. Its just blank, dirt background. I have waited almost 20 minutes but nothing happened.
    I have tried it with an another world, with an old version, tried deleting it and installing but I can't seem to get in a world. I can open other packs. I have allocated 5 GBs of rams and then I tried 6.5 GBs but It doesn't work.

    Please help!

**Comment by Vaelzan** [comment]
This is the issue tracker for Valhelsia: Origins. Valhelsia 3 support is handled via our Discord server.
